# Generated by Django 6.0.1 on 2026-03-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='status',
        ),
        migrations.AddField(
            model_name='assignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='priority',
            field=models.CharField(max_length=20),
        ),
    ]
