# Generated by Django 6.0.3 on 2026-03-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_task_created_at_alter_assignment_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
