# Generated by Django 6.0.3 on 2026-03-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
